# Generated by Django 3.1.2 on 2021-06-16 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca producto')),
                ('formato', models.CharField(blank=True, max_length=20, null=True, verbose_name='Formato')),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo del producto')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre producto')),
                ('valor', models.IntegerField(verbose_name='Precio producto')),
                ('imagen', models.ImageField(null=True, upload_to='Productos', verbose_name='Imagen')),
                ('categoriapro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaginaWeb.categoria', verbose_name='Categoria producto')),
            ],
        ),
    ]
