# Generated by Django 3.1.2 on 2021-06-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaWeb', '0004_auto_20210616_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='producto', verbose_name='Imgamen producto'),
        ),
    ]
