# Generated by Django 3.1.2 on 2021-06-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaWeb', '0005_auto_20210616_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='producto', verbose_name='Imagen producto'),
        ),
    ]
